### ISSUE TITLE
Custom attributes stored in DynamoDB disappear at random.

### ISSUE THREAD

**Issue by kevinkey619b** [alexa/alexa-skills-kit-sdk-for-nodejs#126]
Hi,

Is anyone else experiencing custom attributes stored in DynamoDB disappearing at random?

I'm using very simple code to set the attributes:

this.attributes.myCustom = '1234';
self.emit(':saveState', true);

The above lines are (supposedly) only executed during a very specific intent. Sometimes the data persists in DynamoDB for a few days and other times it last for hours, and sometimes it disappears in 15 minutes.

When the data goes away, the mapAttr values in the database becomes {}

Has anyone else experienced this?

**Comment by knowlsie** [comment]
Not had this issue personally. Do remember however, that the SDK will save your attributes at the end of the session anyway, independently of whether you call `this.emit(':savestate'). As a result, I'd make a pretty good guess that your other sessions (that don't emit ':savestate') may still be overwriting your attributes...  (I personally would avoid using ':savestate:' altogether, and just use that 'saving attributes at the end of sessions' functionality, because of https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/88.)

If it's something other than that, it's almost certainly not an issue with the SDK code, so this may not be the best place to ask. Leave this issue open for now anyway in case any other skill devs happen to have experienced this.

**Comment by knowlsie** [comment]
On the other hand, I can confirm that stuff in DynamoDB *doesn't* just disappear at random.

**Comment by kevinkey619b** [comment]
@knowlsie Yeah, after further investigation I found that the attributes only disappear when my skill exits abnormally. Going to close this.

**Comment by knowlsie** [comment]
Good to hear you solved it.
