### ISSUE TITLE
When testing with Mocha and DynamoDB enabled skill getting "Missing region in config"

### ISSUE THREAD

**Issue by MrAGi** [alexa/alexa-skills-kit-sdk-for-nodejs#134]
I have been experimenting with writing some unit tests with mocha and alexa-conversation (and also mocha/chai) and I kept coming across a "Missing region in config" error whenever I ran the tests.

I have tracked this down to the fact that I am setting a dynamoDBTableName in my handler. I have been able to work around this by adding a line to `DynamoAttributesHelper.js`:

```
aws.config.update({region: 'eu-west-1'});
```

this is directly under the call to require `aws-sdk`.

Presumably there should be a better way of setting this region without modifying the actual package source? Am I missing something or is this an actual issue?

**Comment by daemonsy** [comment]
Hi @MrAGi I bumped into the same issue trying to implement local testing. It's like you said, its due to setting `dynamoDBTableName`. This triggers the helper to create the tables etc, that's not going to work locally. 

There's a [dynamoDB local](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html)  that allows you to write tests as though you have a real dynamoDB instance. I used it together with a naive [PR](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/pull/140) to expose an interface for using dynamo db locally, [sample code here](https://github.com/daemonsy/nyc-subway/blob/7b6489174a3379c4d6dc1bf9d33203057ae3491b/index.js#L132). 

If this is what you're looking for, how about channeling this towards #139 ?

**Comment by MrAGi** [comment]
@daemonsy glad to know it isn't just me! I haven't a chance to run [dynamoDB local](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html) but seems like exactly what I need.

Forgive my ignorance but not sure how to channel towards #139? I haven't got much experience interacting on GitHub - sorry!

**Comment by daemonsy** [comment]
If my approach works for you, we can close this issue and discuss on #139?

**Comment by MrAGi** [comment]
@daemonsy just to confirm that your [PR](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/pull/140) works well for me.

**Comment by neilsmind** [comment]
@Amazon-tianrenz, saw that you closed this issue 14 days ago. Is it now possible to test in mocha and use DynamoDB local? (I'm not seeing it in the code but could have missed it). 

I did notice that PR #140 has merge issues now. If you need someone to resolve the conflicts and update the PR, I'd be happy to help. (This is important to us for use in Alexa)

**Comment by Amazon-tianrenz** [comment]
Hi, @neilsmind 
I've created action item on internal backlog to track #139 and labeled it as "feature request". Please move to #139 for further discussion on local DynamoDB testing. 
We are constantly reviewing PRs so it would be great if you can update the PR #140 with the latest SDK. 
Regards

**Comment by neilsmind** [comment]
Thanks for the quick reply @Amazon-tianrenz! I'll stop replying here and jump to #139.
