### ISSUE TITLE
Why can you not chain intents?

### ISSUE THREAD

**Issue by lucas-rudd** [alexa/alexa-skills-kit-sdk-for-nodejs#178]
We are working on an Alexa skill as a side project, and frankly it's a pain in the butt to build a large robust application with the Alexa sdk. Why can you not chain intents together? This is a hindrance to commercial large-scale development.

**Comment by bclement-amazon** [comment]
Hi Lucas,
Could you elaborate on what you mean by chaining intents and what your use case is? This may be something we can incorporate into the framework.

**Comment by lucas-rudd** [comment]
Sure. So, we're developing a skill that is fairly comprehensive, and we're thinking a lot about the user experience. 

For example, say I have two intents, 'FileClaimIntent' and 'ScheduleRepairIntent.' The user says 'Alexa, tell `Home Depot` that my washer is broken.' Alexa will do some work, ask the user for more information (slot types) and respond, 'Great, I have filed your claim, would you like me to schedule an appointment with someone to come fix it? The earliest they can be at `your address` is in 20minutes.' We would like the user to be able to simply say 'yes' and then move into the 'ScheduleRepair' intent (perhaps with state information) as if I had simply said 'Alexa, tell `Home Depot` to schedule a repair.'

It doesn't look like something like that is currently possible. And so, Alexa will say 'If you would like to schedule a repair, say "Tell `Home Depot` to schedule a repair."'

This is problematic for a couple of reasons.

1: We can emit the intent, and Alexa will go to it, but when we attempt to delegate back FROM the new intent, Alexa seems to act as if she still has state information about the first intent and attempts to delegate from it rather than the new intent.
2: Some intents (in my opinion) ought to be 'Private' and only reachable from a 'Public' intent. These can be methods, but by using methods we lose slot information and a lot of the work Alexa is already doing for us. So, if we create an intent, it is automatically exposed to the user to be called directly. This is not always desirable

**Comment by realharry** [comment]
@lucas-rudd My two cents.

AFAIK, ASK does not have the concept of "chaining" per se. It is something the developer has to do by maintaining the "state". In some cases, it's not easy. For example, handling Amazon.YesIntent is one of the most complicated tasks in my view. (When the user says "yes", what does that mean? You, as a developer, have to maintain the internal state, and understand what "yes" means in the proper context.)

For your point 1., I'm not sure if I understand. In the ASK framework, all intents are independent. There is no concept of a dialog or conversation in the framework. It is you, the developer, who ties these intents together to make it look like a conversation, or question and answer, etc. If you feel like Alexa has state information, that's because you, the developer, put it there.

For your point 2., I think you are mixing intents and handlers. Intents are by definition all public. But, you can have (private) handlers that do not necessarily correspond to intents.

In a sense, the closest thing to "chaining" in the current ASK is `emitWithState()`. You can call a handler from another handler.

**Comment by Amazon-tianrenz** [comment]
Thank you @realharry for the explanation!
Hi @lucas-rudd,
For the described situation, I think the best solution in SDK is ``emitWithState()``. You can have ``AMAZON.YesIntent`` to delegate the request to ``ScheduleRepairIntent`` with all session attributes persisted. 
You can also use different state values to separate the logic in ``AMAZON.YesIntent`` so that it will have different logic under different user interactions.
I'm closing this issue for now. Please feel free to reopen if problem is not solved. 
Regards

**Comment by westlakem** [comment]
how do you access emitWithState?  it's not built into the `handlerInput.responseBuilder`
