### ISSUE TITLE
Alexa Certification issue.

### ISSUE THREAD

**Issue by ashoksva** [alexa/alexa-skills-kit-sdk-for-nodejs#202]
hi,

I have submitted one alexa skill for certification. It got rejected for various reasons. I need to understand 2 of them,

1>Issues with skill endpoint validation
Future versions of the Alexa Skills Kit may add new properties to the JSON request and response formats, while maintaining backward compatibility for the existing properties.  When we invoke the skill with additional parameters, the skill is rejecting it when we expect this to be accepted.  Your code must be resilient to these types of changes. For example, your code for de-serializing a JSON request must not break when it encounters a new, unknown property.

2>The skill consistently returns an error when it is launched. 
Steps To Reproduce:
User: "Alexa, open/start/launch ABC Skill"
Skill: "There was a problem with the requested skill's response"
**Note: The skill gives an error response when launched modally.**?? 

I don't have echo device yet. When i am testing in simulator i am getting no error. 
What is Launching Modally? How do i do it?

Thanks

**Comment by JennJin** [comment]
Hi there. 

1) It sounds like your code is validating the contents of the Request JSON. As additional functionality is added, new parameters will be included, so your code shouldn't reject a Request because of extra parameters. It should accept it and validate the parameters that it uses/needs and ignore the rest.

2) The Simulator is intended as a light weight testing tool to test the Request and Response JSON. If you had a device, you would see the details of the error in a Card in the Alexa App.
There are ways to test a Voice interaction like through echosim.io or a mobile App like reverb.io.

On a side note, the [Alexa Developer Forum](https://forums.developer.amazon.com/spaces/165/index.html) would be a better place to ask questions about Certification Feedback. There are more members who can help answer your questions or provide guidance.

**Comment by Amazon-tianrenz** [comment]
I'm closing this issue now for housekeeping. Please feel free to reopen if issue persists. Cheers
