### ISSUE TITLE
State doesn't get saved if you return to start state

### ISSUE THREAD

**Issue by tomh05** [alexa/alexa-skills-kit-sdk-for-nodejs#21]
Start state is represented by having a blank state variable. Switching to another state works fine, but if you try to switch back to the start state, it never gets saved.

I suspect this is caused by the following line in `/lib/response.js:93`:
```
            if(this.handler.state) {
                this.handler.response.sessionAttributes['STATE'] = this.handler.state;
            }
```
seeing as the expression evaluates to false for an empty string, the STATE attribute never gets updated. Does this `if` statement really need to be there?

**Comment by xinluoxl** [comment]
The 'if' statement should be there because DynamoDB does not allow to save empty strings, you'll get an error 'One or more parameter values were invalid: An AttributeValue may not contain an empty string'. 

To solve this problem, my suggestion is to create a state (like a state named start state) that represents the blank state, every time you want to return to the blank state, go to the state you created.

**Comment by tomh05** [comment]
Ah, okay. I guess then you end up needing two start states - one for "if there's no state variable set" and another for "if moving to start state from a different state". Perhaps there's a way to 'redirect' states automatically so if you open a session with no state variable set, it forwards you to the home state...

Thanks for your help.
