### ISSUE TITLE
Suggestion: Update docs to match current version regarding emit responseready vs ask, tell

### ISSUE THREAD

**Issue by talkingnews** [alexa/alexa-skills-kit-sdk-for-nodejs#219]
In the current version of the SDK and style guides, responseReady is the preferred way to emit a response. Indeed, most of the recent cookbook commits are "updating ask and tell to responseReady".

However,  `this.emit(':ask' and this.emit(':tell'` are frequently and inconsistently used within the  README.MD, and I can now see that, as a newbie a couple of months ago, this was one of the things that confused me. It would probably help new newbies to update this guide for consistency? (I'd do a pull request but they don't get merged so I'll doing this instead).

**Comment by Amazon-tianrenz** [comment]
Hi @talkingnews 
Thanks for the suggestion! I will create a backlog item to track this issue!

Regards!

**Comment by talkingnews** [comment]
Hi there, I was about to ask how this was coming along, when I saw that in another reply, you said:
"We are currently in the process of redesigning the sdk".

Do you know what the timeframe is on this? Am I safe to keep developing with this version, or should I leave it for a few days? I mean, are we talking days, weeks, or possibly months?

Thanks!

**Comment by Amazon-tianrenz** [comment]
Hi @talkingnews, 

Unfortunately, I'm not supposed to give out timeframe information as it could be easily influenced by other high priority tasks. However, in the meantime, we are still actively maintaining the currently SDK so it's definitely safe to continue developing with it. We are also trying to figure out a new design that would make it easy for users to transit from the original SDK so stay tuned!

Meanwhile, we are also on track of updating the README documentation so that developers using SDKv1 would still have the full tech support!

Regards

**Comment by TianTXie** [comment]
@talkingnews 
Please checkout the latest Readme which includes the description of both methods to emit the response.
Feel free to open a new issue if you have any questions.
