### ISSUE TITLE
Echo Show not sending SessionEndedRequest on timeout.

### ISSUE THREAD

**Issue by bobharrisuk** [alexa/alexa-skills-kit-sdk-for-nodejs#223]
On an Echo Dot my Skill receives a SessionEndedRequest if I do not reply to both the original request for input and the re-prompt. Usual 2x ~8sec delays.  The Echo Dot gives its usual beep as the session times out and the SessionEndedRequest intent is fired with the expected EXCEEDED_MAX_REPROMPTS error code.  

When I run the exact same Skill on my Echo Show, I do NOT get the SessionEndedRequest.  The show stops listening after the usual 2x ~8sec delays, but no beep and the SessionEndedRequest intent is not fired.  

I can add CW logs if required. 

Is anybody else seeing this?

**Comment by TianTXie** [comment]
Hi, @bobharrisuk ,
Could you add the logs you print out?  It would be helpful.
Thanks

**Comment by blueshirts** [comment]
I just came across this issue.  I have been seeing the same behavior.  I don't receive a SessionEndedRequest event using the echo show.  I don't have any other devices to test with at the moment.  Grepping the sdk code I don't even see the string "SessionEndedRequest" anywhere in the source.

**Comment by TianTXie** [comment]
@bobharrisuk @blueshirts ,
The shouldEndSession attribute and session timeouts in echo show is different from echo.
 If there is a reprompt, then the timeout for reprompt is 8 seconds with the microphone open and a blue ring displayed, plus 8 seconds for the customer to respond. If Alexa does not hear a response, then a reprompt is rendered, and the customer is given another 8 seconds to respond. If there is still no response, and shouldEndSession is set to false, the session remains open until the display times out. That is why the SessionEndedRequest is not triggered. 
For more information, check [here](https://developer.amazon.com/docs/custom-skills/display-interface-reference.html#use-of-shouldendsession-attribute-and-session-timeouts).
We will provide a method to set shouldEndSession value in the SDK soon, so that you can set shouldEndSession manually.

**Comment by blueshirts** [comment]
I may be a bit confused.  Is there any emit value that at the current time will result in a SessionEndedRequest event?

**Comment by Amazon-tianrenz** [comment]
Hi @blueshirts, 

According to this [page](https://developer.amazon.com/docs/custom-skills/request-types-reference.html#sessionendedrequest), a ``SessionEndedRequest`` can be triggered if the skill returns an invalid response. 

The key point here is to distinguish a ``SessionEndedRequest`` and a normal exit of session. ``SessionEndedRequest`` is sent when ''abnormal' interruptions happens that cause the session to end, including user initiated by saying "exit" or service/device error. 
A session can also exit when the response sent by skill has ``ShouldEndSession`` set to ``true``. In this cause, the skill is supposed to close the session and no ``SessionEndedRequest`` will be sent

Regards

**Comment by blueshirts** [comment]
Thanks for the explanation. This makes sense.

**Comment by Amazon-tianrenz** [comment]
@blueshirts 
In the case of Echo show, as the [link](https://developer.amazon.com/docs/custom-skills/display-interface-reference.html#use-of-shouldendsession-attribute-and-session-timeouts) that @TianTXie attached, in order to make sure that skill remains responsive for on screen action rather than keeping mic open for voice request, skill session is managed in a ``null`` state. Under this state, the session is kept open until display time out and a ``SessionEndedRequest`` will NOT be triggered

Regards
