### ISSUE TITLE
Setting thermostat mode not replying properly

### ISSUE THREAD

**Issue by umarovt** [alexa/alexa-skills-kit-sdk-for-nodejs#275]
Hi,

when I respond to your service with answer below, Alexa says "Device is not responding". I have double checked my response with your documentation and it seems to be structured correctly. 

Thank you for your help in advance.

{
"context": {
"properties": [
{
"namespace": "Alexa.ThermostatController",
"name": "targetSetpoint",
"value": {
"value": 21,
"scale": "CELSIUS"
},
"timeOfSample": "2018-01-19T15:50:39.070Z",
"uncertaintyInMilliseconds": 500
},
{
"namespace": "Alexa.ThermostaController",
"name": "thermostatMode",
"value": "AUTO",
"timeOfSample": "2018-01-19T15:50:39.070Z",
"uncertaintyInMilliseconds": 500
}
]
},
"event": {
"header": {
"namespace": "Alexa",
"name": "Response",
"payloadVersion": "3",
"messageId": "...",
"correlationToken": "..."
},
"endpoint": {
"endpointId": "..."
},
"payload": {}
}
}

**Comment by susanxie123** [comment]
Hi, this could happen due to many reasons, eg. your response was not in time, you did not provide the correct correlationToken, your echo device was offline, etc. It's hard to tell what the problem was without more information. How did you interact with Alexa? What was the exact wording of her reply? Could you reproduce the issue?
