### ISSUE TITLE
Not able to keep a process running in background after returning response

### ISSUE THREAD

**Issue by ChemaMX** [alexa/alexa-skills-kit-sdk-for-nodejs#368]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
You should be able to keep a side process running after you return a response. Example code below. I am using a library that runs a setTimeout to keep a queue open to send logs.

## Current Behavior
When I initialize the library logger it will have a setTimeout running in the background asynchronously to wait for a queue to fill out and send the logs. The problem is that after I return the response back on my intent handler, it won't send the response back to alexa, it keeps running and times out. Then when the background process executes after the setTimeout finishes, a new request is automatically created with an empty intent and I get a RequestHandlerChain not found! error.

## Possible Solution
On alexa sdk for nodejs V1, this was not a problem. I was able to use the library without issue. The background process would keep running fine and the request would be completed with the correct response without disrupting the setTimeout process running in the background. Is there a way to do that now with V2?. Example code below on how to reproduce the issue.

## Steps to Reproduce (for bugs)
JSON request payload:
```
{
	"version": "1.0",
	"session": {
		"new": true,
		"sessionId": "amzn1.echo-api.session.XXXXXXX",
		"application": {
			"applicationId": "amzn1.ask.skill.XXXXXXXXX"
		},
		"user": {
			"userId": "amzn1.ask.account.XXXXXX",
			"accessToken": "XXXXXXXXXXXXXXXXX"
		}
	},
	"context": {
		"AudioPlayer": {
			"playerActivity": "IDLE"
		},
		"Display": {},
		"System": {
			"application": {
				"applicationId": "amzn1.ask.skill.XXXXXXX"
			},
			"user": {
				"userId": "amzn1.ask.account.XXXXXXX",
				"accessToken": "XXXXXXX"
			},
			"device": {
				"deviceId": "amzn1.ask.device.XXXXXXX",
				"supportedInterfaces": {
					"AudioPlayer": {},
					"Display": {
						"templateVersion": "1.0",
						"markupVersion": "1.0"
					}
				}
			},
			"apiEndpoint": "https://api.amazonalexa.com",
			"apiAccessToken": "XXXXXXXXXXX"
		}
	},
	"request": {
		"type": "IntentRequest",
		"requestId": "amzn1.echo-api.request.XXXXXXXX",
		"timestamp": "2018-04-27T18:04:20Z",
		"locale": "en-US",
		"intent": {
			"name": "TestIntent",
			"confirmationStatus": "NONE"
		},
		"dialogState": "STARTED"
	}
}
```
Lambda code:
```
'use strict';

const Alexa = require('ask-sdk');

var test = setTimeout(function () { console.log('done timeout'); }, 10000);

/* INTENT HANDLERS */
const TestIntentHandler = {
    canHandle(handlerInput) {
        const request = handlerInput.requestEnvelope.request;
        return request.type === 'IntentRequest' && request.intent.name === 'TestIntent';
    },
    handle(handlerInput) {
        return handlerInput
            .responseBuilder
            .speak('I shoud be done now.')
            .getResponse();
    }
};

/* LAMBDA SETUP */
const skillBuilder = Alexa.SkillBuilders.custom();
exports.handler = skillBuilder
    .addRequestHandlers(
    LaunchRequestHandler,
    MuteIntentHandler)
    .lambda();
```

## Context
We use an internal logger that when initialized runs a background process: <code>setTimeout(function () { return _this._flush(); }, 60000);</code>. This was working fine in the alexa skd V1 and now is broken with sdk V2. We are blocked by this to continue developing our application.

## Your Environment

* ASK SDK for Node.js used: 2.227.1
* Operating System and version: Windows 10 with Visual Studio 2017. Code running on AWS lambda.

## Node.js and NPM Info
* Node.js version used for development: 8.10
* NPM version used for development: 5.8

**Comment by tianrenz** [comment]
Hi @ChemaMX , 

Could you please provide the expected output log? 

Besides, in the code snippet above, it looks like your `TestIntentHandler ` was not registered in the `skillBuilder`. Instead, `LaunchRequestHandler` and `MuteIntentHandler` was registered. Could you provide code snippet for these two handlers as well if they are also involved in the issue mentioned above?

Regards,

**Comment by ChemaMX** [comment]
Sure, I just actually changed the name of the intent handler on purpose so it will be clearer, forgot to update the skillBuilder as well but it is just the name. The code should be like this:
```
'use strict';

const Alexa = require('ask-sdk');

/* INTENT HANDLERS */
const MuteIntentHandler = {
    canHandle(handlerInput) {
        const request = handlerInput.requestEnvelope.request;
        return request.type === 'IntentRequest' && request.intent.name === 'MuteIntent';
    },
    handle(handlerInput) {
         setTimeout(function () { 
             //do something after 10 seconds. 
         }, 10000);

        return handlerInput
            .responseBuilder
            .speak('I shoud be done.')
            .getResponse();
    }
};

/* LAMBDA SETUP */
const skillBuilder = Alexa.SkillBuilders.custom();
exports.handler = skillBuilder
    .addRequestHandlers(
    MuteIntentHandler)
    .lambda();
```

Not sure exactly what you mean by the expected output log. I added the <code>console.log('done timeout')</code> just as an example, but it should actually be anything, just a process that will run in the background. The idea is basically that a side background process can run without interrupting the alexa request -> response flow.

If you run the above code and trigger the MuteIntentHandler, alexa will reply with a "There was a problem with the requested skill's response" instead of saying "I should be done." as it would be expected. This because the
<code><pre>
var test = setTimeout(function () { 
    //do something after 10 seconds. 
}, 10000);
</pre></code>
is still running even though the response was already sent back. That used to work on alexa sdk V1.

**Comment by tianrenz** [comment]
Hi @ChemaMX , 

This is a very interesting behavior. I took some time to play with it and I think i find the root cause. I'll try explain the though process below and attach a couple links i find that helps solve the problem. 

## Test
First, below is the handler i used for testing: 
```
const LaunchRequestHandler = {
  canHandle(handlerInput) {
    return handlerInput.requestEnvelope.request.type === 'LaunchRequest';
  },
  handle(handlerInput) {
      const speechText = 'Welcome to the Alexa Skills Kit, you can say hello!';
      
      setTimeout(function () { 
        console.log("after 10s");
      }, 10000);
  

      console.log('Should come before');
  
      const response =  handlerInput.responseBuilder
        .speak(speechText)
        .reprompt(speechText)
        .withSimpleCard('Hello World', speechText)
        .getResponse();
        
    return response;
  },
};
```

In the lambda handler, I also print the request event and the response I send back. 

### First run: Node.js 6.10, send back response using callback. 

The log prints: 
```
request
should come before
response
after 10s (printed after 10s )
```
Alexa answers with correct response after 10s.

### Second run: Node.js 6.10, send back response using context. 

The log prints:
```
request
should come before
response
```
Alexa answers with correct response instantly. 

### Third run: Node.js 8.10. Return response directly using async function. 

The log prints: 
```
request
should come before
response
```
Alexa answers with correct response instantly. 

## Conclusion
The conclusion is, the `setTimeOut` was working as expected. The differences is that `callback` of lambda by default will wait until the event loop is empty before freezing the process and returning the results to the caller, while `context` will return the result immediately. 

V2 SDK by default will use callback when you use the `.lambda()` function to create your lambda handler. So it will wait after the `setTimeOut` to finish before returning response to Alexa, which causes the delay. The reason you are receiving an error is because your lambda function also has a timeout setting. Once the process executes longer than the set time period, it will time out and send back an error. 

In v1 SDK, if you didn't pass the callback into the skill, it will use context instead, which I suspect is why it was working before. 

## Solution
1. You can set `context.callbackWaitsForEmptyEventLoop` to `false` to force callback to return result without waiting for event loop to finish, which should resolve your problem. 
2. You can update the lambda to use the Node 8.10 runtime and use async function to return the response. You can check out this [documentation](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/wiki/Developing-Your-First-Skill) on how to write the handler. 

## Reference
https://gist.github.com/hassy/eaea5a958067211f2fed02ead13c2678
https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-handler.html
https://docs.aws.amazon.com/lambda/latest/dg/nodejs-prog-model-context.html

**Comment by tianrenz** [comment]
Closing the issue for now. Please feel free to reopen if problem persists.

**Comment by ChemaMX** [comment]
I just tested the solution by using the Node.js 8.10 and using an async function and I can confirm that it solved my issue. Thanks @tianrenz for the prompt response.

**Comment by helpfordev** [comment]
Hello, I have the same problem by testing.
My LaunchRequest is working and then I test my intent but it never run.

message: Sorry, your skill got this error. RequestHandlerChain not found!

Thats my intent: 
`const setobjectHandler = {
    canHandle(handlerInput) {
        return handlerInput.requestEnvelope.request.type === 'IntentRequest'
            && handlerInput.requestEnvelope.request.intent.name === 'SaveIntent';
    },
    handle(handlerInput) {

        const request = handlerInput.requestEnvelope.request;

        const currentIntent = request.intent;
        if (request.dialogState && request.dialogState !== 'COMPLETED') {
            return handlerInput.responseBuilder
                .addDelegateDirective(currentIntent)
                .getResponse();
        }

        let sessionAttributes = handlerInput.attributesManager.getSessionAttributes();

        let slotStatus = '';
        let object = {};

        //   SLOT: object
        if (request.intent.slots.object && request.intent.slots.object.value && request.intent.slots.object.value !== '?') {
            object = request.intent.slots.object.value;
            slotStatus += ' slot objekt was heard as ' + object + '. ';
            sessionAttributes['bookmark'] = object;

        } else {
            slotStatus += ' slot object is empty. ';
        }

        handlerInput.attributesManager.setPersistentAttributes(sessionAttributes);

        let say = 'Ich habe folgendes gespeichert ' + object + '. what else can I help you with?';

        return handlerInput.responseBuilder
            .speak(say)
            .reprompt('Try again. ' + say)
            .getResponse();
    }
};`

**Comment by tianrenz** [comment]
Hi @helpfordev , 

Could you verify that your intent request name matches the name ``SaveIntent``?  and Could you verify that you registered this ``setobjectHandler`` with ``skillBuilder.addRequestHandlers()``?

Regards
