### ISSUE TITLE
Alexa Skill Kit should either update a documentation or escape characters

### ISSUE THREAD

**Issue by dealancer** [alexa/alexa-skills-kit-sdk-for-nodejs#369]
This is a follow up of https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/306#issuecomment-369202606 since I can't reopen it.

Alexa Skill Kit behaves weird. It does not escape any XML characters, which makes Alexa to fail sometimes. The problem occurred for me when I was sending Alexa contents of RSS feed I do not control.

In case if it is a bug, it should be fixed, in case if it is a feature, developers should be aware about this, so the documentation needs to be updated.

**Comment by brendanclement** [comment]
Vadym,

The challenge with escaping XML characters is that could have some undesired behaviour.  Consider the case where the user provides short-form audio a la. `Hey there, listen to this. <audio src="https://some-cool-sound.com/sounds/1234" />  wasn't that a cool sound`

If we XML escaped the response.. the sound wouldn't play and Alexa would start reading out some URL.  It'd also be a breaking change to the SDK.

Which guide/docs were you following?  we can definitely add a note.

**Comment by dealancer** [comment]
@brendanclement 

yeah, it makes sense. I am not sure where the original documentation is. It looks like it is gone. I was able to find a copy of it here: https://www.npmjs.com/package/alexa-sdk.

**Comment by tianrenz** [comment]
Hi @dealancer ,

The documentation pointed out how the response builder handles xml characters [here](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/master/Readme.md#tips).

Regards

**Comment by alex-mtx** [comment]
Hello all,
We are implementing a Skill with C#, and could find the root cause of the & problem in the Node.js repo.
That tips should be on the [official ssml documentation](https://developer.amazon.com/docs/custom-skills/speech-synthesis-markup-language-ssml-reference.html).
One implementing it with another programming language may easily miss that the ssml is all about XML markup within a Json response (as we did). 
What should one do in order to have it available in the main SSML docs?
Thank you.
