### ISSUE TITLE
ask deploy to eu-west with skill.json

### ISSUE THREAD

**Issue by dkl3in** [alexa/alexa-skills-kit-sdk-for-nodejs#407]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[x] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior

the lambda function and db server will be deployed at eu-west

## Current Behavior

It is only possible to init deploy at us-west, i couldn't figure out to deploy at eu-west

## Possible Solution
```
// Not required, but suggest a fix/reason for the bug,
// or ideas how to implement the addition or change
```
only way is to setup a lambda server by hand at eu-west and insert the endpoint into the skill.json,
but that isn't a great solution.

## Steps to Reproduce (for bugs)
```
// Provide a self-contained, concise snippet of code
// For more complex issues provide a repo with the smallest sample that reproduces the bug
// Including business logic or unrelated code makes diagnosis more difficult
```
my aws profile is set to:  
region = eu-west-1

## Context

I want to build a german alexa skill with echo buttons, but i cant deploy the example to eu-west.
Couldn't find a good documentation about that topic

## Your Environment

* ASK SDK for Node.js used: 1.0.15 and 2.0.5
* Operating System and version: osx 10.13.5

## Node.js and NPM Info
* Node.js version used for development: 8.10.0
* NPM version used for development: 6.1.0

**Comment by tianrenz** [comment]
Hi @dkl3in , 

This seems to be a non-SDK related issues. We would recommend to post on [Alexa user voice forum](https://forums.developer.amazon.com/spaces/165/index.html). Meanwhile, I've forwarded this issue to the corresponding team.

Regards

**Comment by dkl3in** [comment]
Hi @tianrenz,
thanks for the feedback, I will try a post on Alexa user voice forum.
But maybe it it an issue for the documentation, i couldn't find an information how to deploy with the ask-cli at another region as us-west.

Best Regards
Dennis

**Comment by RonWang** [comment]
Hi @dkl3in ,

From the current implementation of ask-cli, the region of Lambda is determined by the endpoint region you are using. We have an internal mapping between the endpoint region and Lambda region. For example, if your endpoint is at region EU, the Lambda will be created at eu-west-1.
We don't read from config file as at that time aws-sdk didn't support read from the config file. We will have a regionProviderChain since aws-sdk does provide ways to set region now. (https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/setting-region.html)

To solve your problem, we suggest you create Lambda at your desired region first and reference it in skill project. The easiest way should be: 

1. Update the skill using "ask api update-skill" or through ASK developer portal with your desired Lambda ARN.
2. Run "ask clone" with skillId to download the project to local.

Let me know if you have further questions!
Ron
