### ISSUE TITLE
Question: how to run asynchronous call after speech response

### ISSUE THREAD

**Issue by jamiesteven** [alexa/alexa-skills-kit-sdk-for-nodejs#41]
I'm trying to run an asynchronous API call after Alexa has completed speaking / playing an audio file. I'm playing a 30 second mp3 file to provide feedback to the user. I'd like the asynchronous call to run after that audio file (or potential speech reply) is completed playing:

```
MyFancyIntent: function() {
  this.emit(':tell', '<audio src="https://s3.amazonaws.com/bucket/30secondsound.mp3" />')
  var self = this

  makeAPIRequest('doSomething') => {
   // end session, and ideally respond again:
   self.emit(':tell', 'All done')
  }
}
```

Right now the session ends after the emit. I'm guessing that maybe I could accomplish this with a custom function that doesn't end the session, replacing the first :tell? If that's correct, I'd very much appreciate some guidance on how to do so.

**Comment by deegles** [comment]
It is not possible to send two responses in a row, since the first `:tell` will end the session. Using `:ask` won't end the session but will prevent anything after that from running.

If your API request will take a significant amount of time, a better pattern would be to process it asynchronously and have a way to check the status of the request.

Another option would be to use the [Long Form Audio](https://developer.amazon.com/public/community/post/Tx1DSINBM8LUNHY/New-Alexa-Skills-Kit-ASK-Feature-Audio-Streaming-in-Alexa-Skills) feature, and keep queuing short clips of audio until processing is complete.

**Comment by jamiesteven** [comment]
Thanks. The async API request actually only takes a second or two. The
audio file is intended to be a delay prior (user feedback) to running the
request. To be more specific, the sound is a 60 second sound prior to
arming an alarm system.

I was thinking I could use an ask that would play the sound. After that
Alexa would listen for an answer; I could accept a cancel request, but if
Alexa hears nothing she could execute the API call on a subsequent intent?

**Comment by deegles** [comment]
You could catch that in the `SessionEndedRequest` and inspect the `reason` parameter to know if the user stopped responding.

**Comment by jamiesteven** [comment]
Good suggestion, thank you. Closing this out.
