### ISSUE TITLE
Add support for simple audio playback

### ISSUE THREAD

**Issue by timheuer** [alexa/alexa-skills-kit-sdk-for-nodejs#45]
While the SDK now has basic support for tell/ask, it should have equivalent simple support for audio playback int he simplest form (play)

**Comment by nicolaerusan** [comment]
I submitted a pull-request that supports basic play behavior as 

this.emit(':audioPlayerPlay', speechOutput, playBehavior, streamUrl, streamToken, streamOffsetInMiliseconds);

So an example would be:

this.emit(':audioPlayerPlay',
        'The #1 song on this day in 1950 was Lucy Lee Peggy Send me home!',
        'REPLACE_ALL',
        "https://archive.org/download/testmp3testfile/mpthreetest.mp3",
        'token-identifier',
        0);

@deegles as the inputs list for these response types gets longer it might be convenient to pass in a JSON object instead for the params so that you don't need to remember the order when passing objects in & easier to handle optional params:

this.emit(':audioPlayerPlay',
{ 
        speechOutput: 'The #1 song on this day in 1950 was Lucy Lee Peggy Send me home!',
        playBehavior: 'REPLACE_ALL',
        streamUrl:"https://archive.org/download/testmp3testfile/mpthreetest.mp3",
        streamToken: 'token-identifier',
        streamOffsetInMiliseconds: 0
});

**Comment by rmtuckerphx** [comment]
Do you have a completed project on GitHub? Where does the token-identifier come from?

**Comment by TianTXie** [comment]
The skill sample related to audio player is : https://github.com/alexa/skill-sample-nodejs-audio-player. The token-identifier is a token that represents the audio stream which can be any string that doesn't exceed 1024 characters.
