### ISSUE TITLE
how to get unique id of my alexa device across multiple users

### ISSUE THREAD

**Issue by swathionchip** [alexa/alexa-skills-kit-sdk-for-nodejs#455]
Hi All,

I followed below tutorial and created my alexa device.
https://github.com/alexa/avs-device-sdk/wiki/Raspberry-Pi-Quick-Start-Guide

I created 4 devices with different serial numbers and 4 different users using these 4 devices.

Now, I created a custom skill with node.js v8.10 and it should be accessible only for these 4 devices. So I am checking **context.System.device.deviceId**, but all are different. How I can get a unique thing irrespective of user currently using for my alexa device.

Thanks in advance for your valuable suggestions and help

Regards
Swathi

**Comment by sebsto** [comment]
This is not possible. 
The device id is specific to a device, an account, a skill and a specific skill enablement. 
You can think about is as a hash of (device serial number, account number, skill ID and date/time of skill activation)

**Comment by swathionchip** [comment]
If not possible to identify my device in skill, is it possible to send some UUID kind of text always from device  along with user audio and then from AVS to skill's lambda function?

**Comment by nikhilym** [comment]
As @sebsto has mentioned, the SDK cannot provide any unique ID for all devices. If this is a feature request, please post your idea on [User Voice](https://alexa.uservoice.com/forums/906892-alexa-skills-developer-voice-and-vote?category_id=322783). 

I am marking this issue invalid since this is not something that can be provided from the SDK. Please reopen the bug if you have any concerns.
