### ISSUE TITLE
Alexa is not parsing any intent if intent utterances have single word but it works for utterances with more than one word

### ISSUE THREAD

**Issue by nami20** [alexa/alexa-skills-kit-sdk-for-nodejs#460]
Alexa is not parsing any intent if intent utterances have a single word but it works for utterances with more than one word
E.g 
I have two intents in the schema. 
intents 
`{
{
name : learnIntent,
utterances: learn
},
{
name : quizIntent,
utterances: play Quiz
}
}`

Skill asks a question to the user do you want play quiz or learn. In case if the user says 'learn or play quiz' utterances then Alexa processes the request. But In case user says utterances that are not defined in the intent schema and if utterance a single word like dance, jump etc. It should parse and send the detected intent but it didn't parse the request for single word. and works for two or more than two words like 'want to play' or 'of course' then Alexa parse the request with a detected message.

**Comment by nikhilym** [comment]
Hey @nami20 , from the initial review of the issue, this seems to be not an SDK issue. But, to be sure, can you please update the issue following the [template](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/2.0.x/.github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md), so that we can investigate it?

Thanks

**Comment by tianrenz** [comment]
Closing issue due to invalid format. Please reopen with template information filled in. 

Regards
