### ISSUE TITLE
SDK v2 - documentation for Intent/Slot switching.

### ISSUE THREAD

**Issue by skavan** [alexa/alexa-skills-kit-sdk-for-nodejs#464]
Hi,

My (simplified) use case is a Custom Skill with Two Intents:

1. "RegisterDevice" Intent.
This has a single slot: AMAZON.rooms.
> Alexa, tell robot to Register This Device to the Living Room.

The deviceId and the Room Name are saved in persistent attributes.

2. "TurnOnOff" Intent.
> "Alexa, tell robot to turn the Light On."

If I have the room name from the RegisterDevice Intent, I use it. So I can build a final string:
> turn on the Living Room Light.

If I don't have the room name from RegisterDevice Intent, I wish to ask the user for it.
> "Alexa, tell robot to turn the Light On."
     **Response**: "what room are you in?" (switch to Intent #1 and fill in the slot)
> "Living Room"
     **Response**: "I am turning the Living Room Light on. (switch back to Intent 2 and finish up).

I think there are two approaches. 

1. code Intent Switching in the handler.
2. create a request interceptor.

I have hunted high and low, and can find bits pieces here and there, but nothing that is explicit on the code to actually do this little feat.

Any ideas?

**Comment by tianrenz** [comment]
Hi @skavan , 

I would recommend to use dialog management in this scenario. For the ``TurnOnOffIntent`` add a slot for ``AMAZON.rooms`` and mark it as required for intent. Then, put the question "What room are you in" as the elicitation for that slot. This way, you can prompt the user to input the room name when its missing. See this [link](https://developer.amazon.com/docs/custom-skills/dialog-interface-reference.html) for more information. 

We have sample skills that demo how to use the dialog management interface. You can find them [here](https://github.com/alexa/skill-sample-nodejs-decision-tree) and [here](https://github.com/alexa/skill-sample-nodejs-petmatch).

On a side note, please fill in the issue template in the future when opening new issues. This could really help us investigate issues quicker. 

Thanks!

**Comment by skavan** [comment]
Thanks @tianrenz. Sorry about the template. Will do so in the future.

Unfortunately, I don't think I can go down the path you suggest.
I already have a rooms slot in `TurnOnOffIntent`. This is because the user is allowed to say:

> Turn on the Light in the Bedroom,

 even if they are in the living room.
As a result it is an optional slot. The logic is, use the Room slot from the TurnOnOffIntent if it exists, if not, use the "RegisterDeviceIntent" room slot if it exists. If not prompt for room.

So, in the case where there is no Room stored in the "RegisterIntent" and no room provided in the "TurnOnOffIntent", then I need to go get it.
So, I can't see an approach working unless I can switch from Intent 2 to Intent 1 and back again. Either through an intercept or a handler redirect. But I am stumped on how to do that.

**Comment by tianrenz** [comment]
Hi @skavan , 

The problem here i think is, when your skill prompt user for room name in the ``TurnOnOffIntent``, the user response will come back in as a different intent. So, unless your ``RegisterDeviceIntent`` can already catch that, you would need a different intent in your model to handle that answer. 

In this case I would recommend to have a third intent called ``RoomSelectionIntent`` which takes in the user's selection of room and send back prompt for future action accordingly. 

A sample user flow could be: 

In turnning on/off state: 
User: "Tell robot to turn on lights" (TurnOnoffIntent)
Alexa: "which room are you looking for"
User: "Living room" (RoomSelectionIntent)
Alexa: "Okay turning on living room lights now"

In register device state:
User: "Register this light"(RegisterDeviceIntent)
Alexa: "which room are you looking for"
User: "Living room" (RoomSelectionIntent)
Alexa: "Okay registered this light to living room"

The trick here is to store a value to differentiate which state user is in for ``RoomSelectionIntent`` handler to act accordingly. I recommend checking out this [sample](https://github.com/alexa/skill-sample-nodejs-highlowgame/blob/master/lambda/custom/index.js) on how to manage the state in v2 Node.js SDK. 

Regards,

**Comment by skavan** [comment]
Thanks @tianrenz. I have studied your sample...but am still confused by how I switch to RoomSelectionIntent from inside either of the other Intents.

I think I can figure-out the state tracking bit.
But from inside the TurnOnOffIntent handler, how (code) do I have Alexa understand that I want to use the RoomSelectionIntent...and presumably, I use the same type of code to get back to the TurnOnOffIntent.

Sorry if I am being dumb!

**Comment by tianrenz** [comment]
HI @skavan , 

when user says "Living Room", that utterance will be mapped to a ``RoomSelectionIntent`` (assuming your interaction model is setup that way). Then when your skill receives that intent request, it will try to route that to your handler. 

Regards

**Comment by skavan** [comment]
OK - that makes sense and also clears up a fundamental misunderstanding I had/have...
and that is that the intent selection is driven only by the user response, and not by the lambda.
**is this correct?**

So then, I need in RoomSelectionIntent a single utterance {Room} and when the user says the room, hopefully Alexa will figure out which Intent applies..

So, then, Alexa sends me back into my Lambda into my RoomSelectionIntent...and here, if I have saved session attributes from the original TurnOnOffHandler, then I can wrap things up inside the RoomSelectionIntent. 

**Is this a correct understanding?**

**Comment by tianrenz** [comment]
HI @skavan , 

Sorry for late reply. 

Yes, the description above is on point. 

Regards
