### ISSUE TITLE
Creating a room on Discovery?

### ISSUE THREAD

**Issue by paulschuetz** [alexa/alexa-skills-kit-sdk-for-nodejs#468]
Is there a feature planned that rooms get created on Discovery? Right now the user has to do everthing manually. It would be great if you could provide a field with a room-name on Discovery.Response and a room gets created in the users account directly. Google is providing this feature with a 'roomHint' field on SYNC responses.

**Comment by breedloj** [comment]
Howdy! This sounds like a feature request targeted at the Alexa service rather than the SDK itself. If that's the case I recommend going to our [User Voice](https://alexa.uservoice.com/forums/906892-alexa-skills-developer-voice-and-vote?category_id=322783) page and creating a feature request there. Thanks!
