### ISSUE TITLE
Manage Lambda Environment Vars During Deploy

### ISSUE THREAD

**Issue by robwhite4** [alexa/alexa-skills-kit-sdk-for-nodejs#475]
Hey, I wish there was a way to manage lambda variables during the deploy process.  Am I overlooking something?  Or can I get that functionality added to the wishlist?

Thanks in advance!

~Rob

**Comment by nikhilym** [comment]
Hey @robwhite4, can you explain what you mean by lambda variables? 

Also, it would be great if you can update the issue following the [issue template](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/2.0.x/.github/ISSUE_TEMPLATE/ISSUE_TEMPLATE.md) format, so that we can get more context on what you are asking!!

**Comment by tianrenz** [comment]
Hi @robwhite4 , 

I would recommend to post on the [Alexa User Voice Forum](https://alexa.uservoice.com/forums/906892-alexa-skills-developer-voice-and-vote), where we will review top ideas regularly. 

Regards

**Comment by nikhilym** [comment]
Closing the issue. @robwhite4 , please reopen in case you have any question about the SDK. If this is a feature request, please post the recommendation on User Voice Forum, as @tianrenz  suggested and update this issue with the forum link.
