### ISSUE TITLE
SessionAttributes not working with API Gateway Request

### ISSUE THREAD

**Issue by topleft** [alexa/alexa-skills-kit-sdk-for-nodejs#488]
Thanks in advance for taking the time read this. We have been using the SDK successfully and find it very helpful in creating Alexa skills.

## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

When using api gateway to route requests to my lambda, I cannot access `SessionAtributes`. In a previous deployment, using the _arn_ address as the endpoint to allow the Alexa request to reach my lambda this was woking fine. 

## Expected Behavior

When routing requests to the lambda, methods on the event should work as expected, such as `handlerInput.getSessionAttributes`.

## Current Behavior
Instead I get this error when calling `handlerInput.attributesManager.getSessionAttributes()`: 
```
{
    "errorMessage": "Cannot get SessionAttributes from out of session request!",
    "errorType": "AskSdk.AttributesManager Error",
    "stackTrace": [
        "Object.createAskSdkError (/var/task/node_modules/ask-sdk-runtime/dist/util/AskSdkUtils.js:22:17)",
        "Object.getSessionAttributes (/var/task/node_modules/ask-sdk-core/dist/attributes/AttributesManagerFactory.js:75:45)",
        "Object.getUserDataFromEvent (/var/task/lib/accountInfo.js:206:44)",
        "Object.capture (/var/task/lib/captureEvent.js:114:32)",
        "Object.handle (/var/task/intent-handlers/alexa/built-in/ErrorHandler.js:15:18)",
        "GenericRequestDispatcher.<anonymous> (/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/GenericRequestDispatcher.js:210:59)",
        "step (/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/GenericRequestDispatcher.js:44:23)",
        "Object.next (/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/GenericRequestDispatcher.js:25:53)",
        "fulfilled (/var/task/node_modules/ask-sdk-runtime/dist/dispatcher/GenericRequestDispatcher.js:16:58)",
        "<anonymous>"
    ]
}
```
## Differences between the arn endpoint and the API gateway http endpoint:

I am transforming the event:
```
const transformRequest = {
  process: (handlerInput) => {
    let buff = new Buffer(handlerInput.requestEnvelope.body, 'base64')
    let text = buff.toString('ascii')
    const payload = JSON.parse(text)
    handlerInput.requestEnvelope = payload
    return
  }
}

...

  exports.handler = Alexa.SkillBuilders.custom()
  .addRequestHandlers(
    ...
    CustomerHandler,
    ...
    YesHandler,
    UnhandledHandler
  )
  .addRequestInterceptors(transformRequest) // transformation happens here
  .addErrorHandlers(ErrorHandler)
  .lambda()
```

### I have confirmed that:
- The event is being transformed properly (it looks exactly the same as my previous implementation using the arn address)
- `handlerInput.attributesManager` is available

## Context
We are trying to enable API gateway so we have more control over our deployment process. Specifically, when a skill is reviewed and released and its requirements are different than the current release, we need to be sure it is pointing to the correct version of our lambda code.

## Your Environment

*   "ask-sdk-core": "^2.0.9",
*   "ask-sdk-model": "^1.5.0",

## Operating System and version:
* Mac OS: v10.13.6

## Node.js and NPM Info
* Node.js version used for development: v8.10
* NPM version used for development: v5.6.0

**Comment by tkarpeichik** [comment]
good call...they must have encountered this

**Comment by tianrenz** [comment]
Hi @topleft , 

Could you please verify that the transformed request envelope has a `session` filed available?

Regards,

**Comment by topleft** [comment]
@tianrenz thanks for the reply. 

Yes:
```
console.log(handlerInput.requestEnvelope.session)

{
            "new": true,
            "sessionId": "amzn1.echo-api.session...",
            "application": {
                "applicationId": "amzn1.ask.skill..."
            },
            "user": {
                "userId": "amzn1.ask.account.AHMQ...",
                "accessToken": "eyJ0eXA..."
            }
 }
```

**Comment by tianrenz** [comment]
Hi @topleft , 

Based on the interceptor code above, since you are transforming the `requestEnvelope.body`, I'm guessing that you have the API Gateway Lambda proxy setting turned on? Could you verify that please?

 The reason I'm asking is that with lambda proxy setting turned on, the event payload will contain the entire client request as shown [here](https://docs.aws.amazon.com/apigateway/latest/developerguide/set-up-lambda-proxy-integrations.html#api-gateway-simple-proxy-for-lambda-input-format). With that setting turned off, only the body with be sent to your lambda (which in the case of alexa skill, will be the actual request envelope JSON);

The error you are seeing is caused by ``AttributesManager`` trying to look for the `session` field in the specific location. The ``AttributesManager``is initialized when the skill is invoked with the `event` object passed in. In normal cases, `event` object will be the `RequestEnvelope`. `AttributesManager` will look for `event.session` to see if ``session`` is present. If not and `getSessionAttributes()` is invoked, an error will be thrown. In your case, the `event` payload passed in doesn't conform to the `RequestEnvelope` shape, which is causing the error. 

For the solution to this, I suggest checking out the thread [here](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/issues/381#issuecomment-397465538). 

Regards

**Comment by topleft** [comment]
@tianrenz Thanks for the links and explanation. 

Yes, API Gateway Lambda proxy setting turned on.

My issue is that the same input shape worked when calling the lambda by the arn address. I have replicated the JSON coming into the intent handlers. I have confirmed that attributesManager is available. It seems that you are suggesting that the shape of the input needs to be different when using http. Why should the shape of the `handlerInput` need to change depending on the input protocol (arn vs http)?

I was looking [here](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/3f52c59b00ba2110acfab5e440cd9832de3d92d3/ask-sdk-core/lib/attributes/AttributesManagerFactory.ts#L47). Looking at that code, I can only guess that options are being passed differently to that class when using a different protocol to call the lambda. Could that be possible?

**Comment by tianrenz** [comment]
Hi @topleft , 

When using the lambda ARN directly as the skill endpoint, your skill lambda would receive just the RequestEnvelope json. That's different from when you use it through API gateway proxy, which wraps the RequestEnvelope in the body of the full HTTP request. 

Here the shape of `HandlerInput` doesn't need to be changed. However, the parameter that you pass into the `Skill.invoke()` need to be the RequestEnvelope only, because there's some initialization logic that requires it (see [here](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/2.0.x/ask-sdk-core/lib/skill/CustomSkill.ts#L73)).  

You can use the following code for your lambda handler and it should be able to fix the problem: 

```
exports.handler = async function (event, context) {
  const responseEnvelope = await skill.invoke(JSON.parse(event.body),context);
  return {
     "body": JSON.stringify(responseEnvelope)
  };
};
```

Regards

**Comment by topleft** [comment]
@tianrenz  Thanks again for the information and pointing out the construction of the HandlerInput. I will try to find some time to work this out and let you know my results.

**Comment by nikhilym** [comment]
Hey @topleft , did you try out the approach mentioned by @tianrenz ? Please update the issue with your results.

**Comment by topleft** [comment]
@nikhilym I should get some time this weekend to implement it. I will let you know.

**Comment by topleft** [comment]
@tianrenz Feel free to close. We have another solution using the ARN  address and appending the lambda version like so -->  `arn:aws:lambda:region:ACCOUNT_ID:function:FUNCTION_NAME:VERSION`
