### ISSUE TITLE
Forward request to new intent

### ISSUE THREAD

**Issue by westlakem** [alexa/alexa-skills-kit-sdk-for-nodejs#499]
## I'm submitting a...

<pre><code>
[X] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
Need the ability to emit to a new intent in V2, while switching dialog & intent in the request to the new intent.

## Current Behavior
Currently no way to switch intents (or "forward" the request) and have it modify the request object so dialog works properly.

## Steps to Reproduce (for bugs)
Create 2 intents, both with required & different slots
Call the first intent
In the first intent, send the request to a different "handle" function
In the 2nd intent, call "Delegate"
It tries to fill the slots for the first intent

## Context
This will need fixed in all versions of the SDK, including Node, Python, JAVA,Ruby, etc.

**Comment by tianrenz** [comment]
Hi @westlakem , 

Currently, the skill can't proactively change the intent. The switching of intent request needs to be triggered by user utterance (That is, user says something different). The "forwarding" feature in the v1 SDK will only allow for sending the SAME request to different handle function. But it doesn't actually change the intent content. 

Regards

**Comment by Bubelbub** [comment]
But sorry @tianrenz, I want to implement Amazon Pay now.
And then I have this workflow.

`Order Intent` -> `Connections.Response` -> How get back? `Order Intent`

In order intent I'm returning a `Connections.SendRequest` directive.
Then my response / next intent is `Connections.Response`.
And how to get back to my `Order Intent`?

Yes I'm able to use something like `OrderIntent.handle(handlerInput)` BUT when I'm at the Cart I can't use `addConfirmIntentDirective` because it thinks its a `Connections.Response`.

I can't use the `Dialog` directives with a changed `name` of `updateIntent` because the Dialog directives not allowing to change the name.

**Comment by franklin-lobb** [comment]
@Bubelbub what's the user flow you're trying to achieve?  I would think you'd want to confirm order intent prior to sending the Connections.Request to AmazonPay.  (I'm presuming this includes the order details.)  If you capture what you need to retain in persistent attributes (could be the entire request!) before making the request to Amazon Pay, you'll have access to it when it returns.  If you really need to ask a yes/no question immediately upon returning, you can do that and include the AMAZON.YesIntent (and NoIntent) in your interaction model

**Comment by tianrenz** [comment]
Closing the issue due to inactivity. Please feel free to reopen if the problem reappear. 

Regards
