### ISSUE TITLE
createStateHandler(s)

### ISSUE THREAD

**Issue by craigbilner** [alexa/alexa-skills-kit-sdk-for-nodejs#5]
Couple of questions:

Should the API be `CreateStateHandlers`?

It's a bit confusing to have code where you create multiple handlers by creating a state handler singular?

```
var startStateHandlers = Alexa.CreateStateHandler(GAME_STATES.START, {
```

Also - in the example, `newSessionHandlers` don't use the above pattern. What's the best practice on this, should all handlers be created and assigned a state key so `GAME_STATES.NEW` ?

Thanks

**Comment by deegles** [comment]
Hi Craig,

We chose 'handler' vs 'handlers' since the function returns a single object that maps to a single state, even though it can contain multiple listeners. You then register event listeners functions inside of that object. Providing an object containing intent listener functions as a parameter to the function is a convenience.

For example, the following is valid:

```javascript
var inProgressHandler = Alexa.CreateStateHandler('InProgress');

inProgressHandler['LaunchRequest'] = function(){ ... }
```

Does that make sense?

As to your other question, in the example, `newSessionHandlers` would be equivalent to 

```javascript
var newSessionHandlers = Alexa.CreateStateHandler(); // The 'null' state

inProgressHandler['NewSession'] = function(){ ... }
```

You would still need to have something like the above to catch the first-ever invocation of the skill, before any attributes (including the state string) have been set.

Of course, you don't have to use the state feature at all, especially if it is a simpler skill. It just helps to manage complexity as the number of intents go up.

**Comment by craigbilner** [comment]
Thanks @deegles,

I guess when I first came to it I didn't see them as "listeners" but rather "handlers", ta.

Still not sure on the "new session being a special case" thing, perhaps if state was the second argument it would have worked out. I actually like the declarative state handley stuff and would have liked to see it used for all states but ok, ta.
