### ISSUE TITLE
Replay dialog and terminate

### ISSUE THREAD

**Issue by reflexdemon** [alexa/alexa-skills-kit-sdk-for-nodejs#505]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
When I try to replay a dialog, I am expecting it to be terminated after the `AMAZON.StopIntent` or `AMAZON.CancelIntent` has been responded. In this way I will be able to run a pre-determined voice commands and add this part of our automation end to end testing. 

## Current Behavior
If I add now to the jenkins it hangs for ever and I had to explicitly kill the job.

## Possible Solution
Option 1: We can have an additional cli argument `--terminat` that will signal the dialog command to terminate after the list of uttrances has been played.
Option 2: Whenever the dialog finds a `AMAZON.StopIntent` or `AMAZON.CancelIntent` part of response, it terminates automatically.

## Steps to Reproduce (for bugs)
Please create a dialog json and run the below command,

```
ask dialog -r test_dialog.json -o logs/output.log
```
For example code refer, https://github.com/reflexdemon/skill-sample-nodejs-hello-world
## Context
I am unable to put the end-to-end integration testing to jenkins.

## Your Environment
OS: `macOS 10.13.6 `
Node: `v8.11.2`
NPM: `6.4.1`
ASK: `1.5.3`

**Comment by RonWang** [comment]
Hi @reflexdemon ,

First thanks for using CLI, especially the usage of integration test through CLI's dialog command. And for your question, the dialog command supports some special commands (https://developer.amazon.com/docs/smapi/ask-cli-command-reference.html#dialog-command). One of the special commands "!quit" is the solution to your problem.

You can add !quit as the last userInput in your test_dialog.json, and the current session will be terminated and CLI will quit the REPL mode. For your option2, we can't always quit when stopIntent kind of intent happens, since this control should belong to user.

Hope this will answer your question,
Ron

**Comment by reflexdemon** [comment]
I would like to reopen the issue. I am getting an error signal and fails my batch.
```
  User  >  !quit
  [Error]: Replay file should not include any special command.
```

Please refer to https://developer.amazon.com/docs/smapi/ask-cli-command-reference.html#replay-file-format

> Ensure your replay file does not includes the special commands "!quit" or "!record", as those will result in an [Error]: Replay file should not include any special command. error message.

**Comment by RonWang** [comment]
I see your issue here now. So the replay file is first designed to auto play the utterances and then let user continue the prior conversation. That's why special command is not considered in current approach. I've forwarded this to our service team, and we will treat it as a feature request to support special command in this flow. I will update here once that's supported in the new release!

**Comment by reflexdemon** [comment]
Any update on this issue?

**Comment by dorian-marchal** [comment]
Any news on this?

**Comment by btburton42** [comment]
Can we get a status update? We have an end-to-end test runner project on hold pending resolution of this issue.

**Comment by RonWang** [comment]
Hey all!

With the [ask-cli](https://github.com/alexa-labs/ask-cli) release to Github (now as [ask-cli-x](https://www.npmjs.com/package/ask-cli-x)), please check the status from issue https://github.com/alexa-labs/ask-cli/issues/56 for further notifications.

Close this issue.
