### ISSUE TITLE
git pull

### ISSUE THREAD

**Issue by nujcharee** [alexa/alexa-skills-kit-sdk-for-nodejs#521]
Hi
I couldn't find anywhere in the documentation to get an equivalent of git pull on Alexa command line. please can you help?
Many thanks

**Comment by RonWang** [comment]
Hi @nujcharee 

This is a really good question so thanks for asking! 
May I first know what's the reason you need this feature? What's the background when you need this functionality?

Thanks,
Ron

**Comment by nujcharee** [comment]
Hi Ron,
During my first alexa skill development I didnt know much what to do but I was familiar with git so naturally my thinking process was pretty much Git. I saw similar commands like `ask push` but there isnt `ask pull`. For example I might do some changes in Lambda and in the core skills part (the skill.json part), I changed codes in VS Code and I can see everything to do with the project but on thru Amazon web browser it wasnt really easy to find whether what im looking is on lambda page, or on different page.


Hope this makes sense. 
Thanks Ron

**Comment by RonWang** [comment]
Hi @nujcharee ,

From your description, I think you really enjoy the developer experience using CLI, where you can concentrate on your VSCode skill project for development. 

And to answer your question: similar to "git diff", you can really try to use "ask diff" command to see what's changed based on your local skill project. This command compares the local project with server version of the skill, so that if you modify your skill in some other places, you can still check what's the difference between local project and latest server version. You can also use the content diff result of "ask diff" as the patch, and run "git apply" to apply the patch to your local project, which indeed performs a "git pull" behavior.

Hope this is helpful for you!
Ron

**Comment by RonWang** [comment]
Closing this issue. Please feel free to reopen if you have any further question!
