### ISSUE TITLE
DynamoDbPersistenceAdapter -- can't await table creation

### ISSUE THREAD

**Issue by jacobweber** [alexa/alexa-skills-kit-sdk-for-nodejs#528]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[X] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
If you pass createTable=true, DynamoDbPersistenceAdapter will create the table in its constructor using an asynchronous call. There's no way to wait for this to finish, so your first call that uses this table will usually fail. It would be better to have a createTable function we could call, which uses a promise or callback so we could wait for it to finish.

## Current Behavior
See above.

## Possible Solution
See above.

## Steps to Reproduce (for bugs)
N/A

## Context
Using persistent attributes.

## Your Environment
* ASK SDK for Node.js used: 2.5.1
* Operating System and version: Mac OS 10.14.3

## Node.js and NPM Info
* Node.js version used for development: 8.12.0
* NPM version used for development: 6.4.1

**Comment by tianrenz** [comment]
Hi @jacobweber, 

Thanks for your input! The decision to put the createTable call inside of the constructor is made out of several concerns. 

First, ``DynamoDbPersistenceAdapter`` isn't used directly by the developer but used internally by the ``AttributesManager``. And since ``AttributesManager`` interface is generic, the underlying storage solution might not support a table creation operation, we can't add the ``createTable`` method to the interface for compatibility concerns. 

Second, in order to ensure that a table will be created for user if there isn't already one. We can only put it in the constructor, or in both get and save calls. However, AWS SDK DynamoDb createTable function call returns before the table is actually up and ready to use. Therefore, to ensure data consistency and avoid failure rate, we can not put it in the save call. Hence the decision to actually call table creation in the constructor. 

Third, why not make it "awaitable"? - The answer is there's no benefit in awaiting the ``createTable`` call to finish since it returns success while the table is still being created. You would still run into failures in the subsequent calls within that time period. 

Regards

**Comment by jacobweber** [comment]
Ah, didn't realize it returned "success" before it finished creating the table.

In theory, it could still be useful to have a createTable function, even if it's not part of the interface. Your application knows the type of adapter object it's using, since it creates it, so it could take advantage of additional methods that aren't part of the interface. But unless there's also a method that tells you whether it finished being created, it might not be very useful.

I'll probably just copy that createTable code into my build script, and create the table at build time instead of runtime.

**Comment by tianrenz** [comment]
Thanks for your input! I'm closing the issue for now. Please feel free to open new issues if you encounter other problems. 

Regards
