### ISSUE TITLE
Viewport no longer available in requestEnvelope

### ISSUE THREAD

**Issue by kenroyandfamily** [alexa/alexa-skills-kit-sdk-for-nodejs#551]
Until a couple of weeks ago I was getting the device's display size (e.g. pixelWidth) via:

handlerInput.requestEnvelope.context.Viewport.pixelWidth

But "Viewport" is now undefined.

If it is no longer available, then how does one get the screen size of a device?

**Comment by ShenChen93** [comment]
Hi @kenroyandfamily ,
Sorry for responding late. I tested my hello world skill on aws lambda, by console.log(handlerInput.requestEnvelope.context.Viewport.pixelWidth), I can correctly get the right value. Please let me know if the problem still exist.

Thanks,
Shen

**Comment by kenroyandfamily** [comment]
The problem still exists.  I am also testing using aws lambda and console.log.  When I log "handlerInput.requestEnvelope.context" there is no "Viewport" at all.  And it is not just me, my beta-testers see the same thing.

This is what "context" logs as:

context: 
{ AudioPlayer: 
{ offsetInMilliseconds: 180880,
token: '742620957',
playerActivity: 'FINISHED' },
System: 
{ application: [Object],
user: [Object],
device: [Object],
apiEndpoint: 'https://api.amazonalexa.com',
apiAccessToken: '<removed>' } },
request: 
{ type: 'AudioPlayer.PlaybackFinished',
requestId: 'amzn1.echo-api.request.<removed>',
timestamp: '2019-06-07T22:24:18Z',
locale: 'en-US',
token: '742620957',
offsetInMilliseconds: 180880 } } { depth: null }

**Comment by ShenChen93** [comment]
@kenroyandfamily May I know what sdk version are you using?

**Comment by kenroyandfamily** [comment]
version 2.5.2

**Comment by ShenChen93** [comment]
Hi @kenroyandfamily,
The viewport property is originally inside the alexa request(context object). From SDK side, we just clone the context object and add it to handlerInput. Therefore, I guess the reason for your problem is the alexa request send to your skill lambda doesn't include viewport information.  From our doc: https://developer.amazon.com/docs/alexa-presentation-language/apl-viewport-characteristics.html,
you can see: The request sent to a skill service includes viewport characteristics when the device supports APL. So, I want to know how you test your lambda code. If you directly tested it with lambda event, you should add the viewport info in your request

**Comment by kenroyandfamily** [comment]
I attempted to upgrade to the next version, but made some mistakes and had to back out.  Now the skill is getting the ViewPort property.  Not sure why.  Perhaps reseting the SDK locally cleared out any bit flip that may have occurred during development?  Just one of those weird things that happens with no reasonable explanation.  Gremlins!?  Thanks for your help :-)  BTW, I'm not quite sure how to upgrade to the next version.

**Comment by ShenChen93** [comment]
Interesting, maybe the version2.5.2 is not well installed in the beginning? Anyway, glad you solve this probelm. I will close this issue, please feel free to reopen it when similar issue happen again.
