### ISSUE TITLE
Alexa Presentation Language and Activity Log

### ISSUE THREAD

**Issue by xuaninbox** [alexa/alexa-skills-kit-sdk-for-nodejs#568]
After switching from Display Interface to APL it no longer shows up in the Activity Log page in the app (You can still find it in the Voice History). Is there a way to use Display Interface with APL?

**Comment by ShenChen93** [comment]
Hey @xuaninbox 

I turned on the APL interface on developer console, and test my skill. All the activities are displayed well in my app's activity log. Did I miss something cause with current info you provided, I cannot reporduce your issue. One more thing I need to check, while writing your lambda function, do you add withSimpleCard option in response builder? Since without card info in response, no log will be displayed in activity logs.

Thanks,
Shen

**Comment by xuaninbox** [comment]
Hey @ShenChen-Amazon Yes I did remove withSimpleCard, does this mean the Display Interface can be used with APL and APL takes priority?

**Comment by ShenChen93** [comment]
Hi @xuaninbox 

I tried to use the display interface and APL at the same time, and APL content shows with priority. However, since SDK doesn't manage the priority, it would be great if you can post your question on https://forums.developer.amazon.com/spaces/165/index.html and get help from Alexa support team..
Closed this issue for now and please feel free to reopen it if you have any concerns. 

Thanks,
Shen
