### ISSUE TITLE
Handling second reprompt 

### ISSUE THREAD

**Issue by indunie** [alexa/alexa-skills-kit-sdk-for-nodejs#580]
Is there any method to handle or use second reprompt?

In my scenario, I want alexa to ask a question related to another intent, if user does not response to the reprompt.
Can someone answer please.

**Comment by ShenChen93** [comment]
Hi @indunie ,

From this [doc](https://developer.amazon.com/docs/echo-button-skills/receive-voice-input.html#reprompts),  alexa will turn off the sessions if there's no response after reprompt. I am sorry our SDK cannot add this feature because it's a limit from the platform.

It would be really grateful if you can log this requirement as a user voice request [here](https://alexa.uservoice.com/forums/906892-alexa-skills-developer-voice-and-vote?category_id=322801). I will c.ose this issue for now, please feel free to reopen if you have any questions.

Thanks,
Shen
