### ISSUE TITLE
Volume up/down

### ISSUE THREAD

**Issue by benrolfe** [alexa/alexa-skills-kit-sdk-for-nodejs#589]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  
[ ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

I've built a Skill that successfully plays a long audio file (~ 30 minutes). When the user (while the audio is playing) says "Alexa, volume up", it gets passed to my "AMAZON.FallbackIntent" handler. 

Shouldn't Alexa handle the volume for me? Or is there a way to control volume using the SDK?

## Expected Behavior
Alexa should increase/decrease the volume.

## Current Behavior
When the user (while the audio is playing) says "Alexa, volume up", it gets passed to my "AMAZON.FallbackIntent" handler. 

## Possible Solution
Can Alexa handle the volume for me while audio is playing?

## Steps to Reproduce (for bugs)
1. "Launch Cornerstone Church Kingston"
2. "Play latest sermon"
3. "Volume up"

## Your Environment

* ASK SDK for Node.js used: 2.7.0
* Operating System and version: Mac

## Node.js and NPM Info
* Node.js version used for development: v10.16.0
* NPM version used for development: v6.12.1

**Comment by nikhilym** [comment]
Hey @benrolfe , 

> Shouldn't Alexa handle the volume for me? Or is there a way to control volume using the SDK?

You are right. Alexa should be handling the volume for you. However, if you are in a skill session, any utterance will try to match to your skill because Alexa doesn't know if the user is talking to the skill or to the service itself. I am guessing your skill session was still open when you were trying the 'volume' options. As for the volume control through SDK, there is no control directives that audioplayer provides that can be utilized by skill developers.

You can check for related questions on the [forums](https://forums.developer.amazon.com/spaces/165/index.html) to see if anyone got a workaround, or ask on the forum itself to get help from the audioplayer service team.

Since this is not an SDK issue, I am closing this one. Please update the issue with the forum post if you get a solution. Thanks.
