### ISSUE TITLE
Device control with Alexa skill

### ISSUE THREAD

**Issue by mduzgun** [alexa/alexa-skills-kit-sdk-for-nodejs#609]
Hi, everyone.
I want to control my Alexa devices using Alexa Skill.
For example, when I say "hello" to Alexa and lights (Sengled brand) are on.
Could I do this using Alexa skill?

**Comment by ShenChen93** [comment]
Hi, @mduzgun 

To use skill to control alexa devices, you may need to build a Alexa smart home skill instead of Alexa custom skill. You could refer to [this doc](https://developer.amazon.com/en-US/docs/alexa/smarthome/understand-the-smart-home-skill-api.html) for more info. Unfortunately , our SDK only work for custom skill right now, and we will bring smart home SDK in future.

Thanks,
Shen
