### ISSUE TITLE
The directive Navigation.SetDestination it's not accepted in the sdk nativally

### ISSUE THREAD

**Issue by guilhermecaixeta** [alexa/alexa-skills-kit-sdk-for-nodejs#619]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[ ] Performance issue
[x] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Context

Currently the Navigation.SetDestination directive type is not offered as a valid type in the Directive type, if we need use this it's necessary do a work around to make possible use it. 

## Your Environment

* ASK SDK for Node.js used: 2.8.0
* Operating System and version: Windows 10

## Node.js and NPM Info
* Node.js version used for development: 12.6.2
* NPM version used for development: 6.14.4

**Comment by ShenChen93** [comment]
Hi @guilhermecaixeta ,

Thanks for reporting this feature request. It seems this feature hasn't been onboard to SDK. We will prioritize it and push model release ASAP. Keep the issue open for now and I will update status here.

Thanks,
Shen

**Comment by guilhermecaixeta** [comment]
Thank you for you answer @ShenChen-Amazon. This will help me a lot.

**Comment by ShenChen93** [comment]
Sorry for the late response. It turns out those directives are wrapped in [ask-auto-sdk](https://github.com/alexa/alexa-auto-sdk) instead of our SDK. But still you could use those directive in your skill code. Sorry for the inconvenient, I know directly api call is not easy to use, we will look into it and provide better user experience.

I will close this issue on our side. Please feel free to reach out if you have more questions :)
