### ISSUE TITLE
Request does not contain resolutionsPerAuthority array

### ISSUE THREAD

**Issue by pkehr09** [alexa/alexa-skills-kit-sdk-for-nodejs#623]
## I'm submitting a...

<pre><code>
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  
[x ] Performance issue
[ ] Feature request
[ ] Documentation issue or request
[ ] Other... Please describe:
</code></pre>

## Expected Behavior
My quiz skill should have my utterance inside the jSON request object, no matter if the utterance is correct, or incorrect. Right?

## Current Behavior
I'm following the quiz tutorial from the Alexa Skills camp Youtube series posted last month and it is not behaving as it does in the tutorial. Only when i give the right answer does it respond correctly. If the answer is wrong, resolutionsPerAuthority inside the request object returns undefined. In the video, it does not. I cannot find the incorrect utterance object inside the jSON response at all to compare to the database. 

## Your Environment
Alexa Dev Console in Node.js

## Node.js and NPM Info
* Node.js version used for development:
* NPM version used for development:

**Comment by ShenChen93** [comment]
Hi @pkehr09 

Thanks for using our SDK ! According to the behavior you logged above, it seems you met some issues in the coming request object. However, since our SDK is just pass through layer without any changes to the original request, so it's should not be a SDK issue. 

I would recommend you to log this issue to [Alexa Forums](https://forums.developer.amazon.com/spaces/165/index.html), where you can get the help from people who have better context on this issue. Close this issue from our side for now, and please feel free to reopen if you have other concerns / questions :)

Thanks,
Shen
